### PR TITLE
Adding https to a bunch of files

### PR DESCRIPTION
**Pull request by barton2526**
adding https where supported + remove suchflex image

### CODE REVIEW

**Comment by barton2526** [comment]
this encompasses many changes to many files, but there should be no cosmetic changes beyond the removal of suchflex from the footer and https links for projects that support SSL.

**Comment by grctest** [comment]
"https://download.gridcoin.us/download/downloadstake/signed/snapshot.zip" doesn't work: https://github.com/gridcoin/Gridcoin-Research/issues/194

**Comment by grctest** [comment]
Why removing the gem lock file? It appears to have more contents than the normal gem file, does the website still serve/build without it?

**Comment by barton2526** [comment]
Resolved gemfile lock

**Comment by barton2526** [comment]
@grctest resolved snapshot url to http for now

**Pull request merged**
